// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN34J47O2d_YJUTb-XAaeelydQzDj6Ij4',
    appId: '1:170525274412:web:f4760448064fc43d2f3c89',
    messagingSenderId: '170525274412',
    projectId: 'flutter-genui-sdk-mcp-12345',
    authDomain: 'flutter-genui-sdk-mcp-12345.firebaseapp.com',
    storageBucket: 'flutter-genui-sdk-mcp-12345.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd5CxtlY7W5Kq7wIBmkq7sY6pTenvSmjU',
    appId: '1:170525274412:android:02473a3b4da669502f3c89',
    messagingSenderId: '170525274412',
    projectId: 'flutter-genui-sdk-mcp-12345',
    storageBucket: 'flutter-genui-sdk-mcp-12345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN34J47O2d_YJUTb-XAaeelydQzDj6Ij4',
    appId: '1:170525274412:ios:02473a3b4da669502f3c89', // I don't have iOS appId yet, but I'll use placeholders
    messagingSenderId: '170525274412',
    projectId: 'flutter-genui-sdk-mcp-12345',
    storageBucket: 'flutter-genui-sdk-mcp-12345.firebasestorage.app',
    iosBundleId: 'com.example.flutterGenuiSdkFirebaseMcp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN34J47O2d_YJUTb-XAaeelydQzDj6Ij4',
    appId: '1:170525274412:ios:02473a3b4da669502f3c89',
    messagingSenderId: '170525274412',
    projectId: 'flutter-genui-sdk-mcp-12345',
    storageBucket: 'flutter-genui-sdk-mcp-12345.firebasestorage.app',
    iosBundleId: 'com.example.flutterGenuiSdkFirebaseMcp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN34J47O2d_YJUTb-XAaeelydQzDj6Ij4',
    appId: '1:170525274412:web:f4760448064fc43d2f3c89',
    messagingSenderId: '170525274412',
    projectId: 'flutter-genui-sdk-mcp-12345',
    authDomain: 'flutter-genui-sdk-mcp-12345.firebaseapp.com',
    storageBucket: 'flutter-genui-sdk-mcp-12345.firebasestorage.app',
  );
}
